## data
train_dir: /home/guest/r11944026/research/ic-ralm-odqa/in-context-ralm/reproduce_retrieval/result/nq-train
dev_dir: /home/guest/r11944026/research/ic-ralm-odqa/in-context-ralm/reproduce_retrieval/result/nq-dev
train_file: formatted-ms2.nq-train.json
dev_file: formatted-ms2.nq-dev.json
dataset_name: nq
data_size: "debug"
index_dir: embeddings/dpr # embeddings/contriever
# "full": (train, dev) = (~79K, ~8K), "1/10": (train, dev) = (10K, 1K), "debug": (train, dev) = (50, 10)
gold_dev_answers_path: results/nq-dev-answers.json

## model
encoder_type: dpr # dpr, contriever, bert...
resume_training: 
resume_path:
resume_wandb_id:
doc_encoder: facebook/dpr-ctx_encoder-single-nq-base # facebook/contriever 
# query_encoder: wandb/run-20240513_225200-ja1uhk3w/files/step-2506/query_encoder/
query_encoder: facebook/dpr-question_encoder-single-nq-base
lm_model: huggyllama/llama-7b
# gpt2, google/flan-t5-large, huggyllama/llama-7b
## training
model_parallelism: False
max_round: 1
k: 1
per_device_train_batch_size: 2
train_llm_batch_size: 8
per_device_eval_batch_size: 6
eval_llm_batch_size: 6
max_train_epochs: 1
num_exemplars: 3
# debug: set num_worker=0, pin_memory=False
temperature: 0.1
num_workers: 4
pin_memory: True
auth_token: None
cache_dir: cache
adam_eps: 1.0e-8
weight_decay: 0.0
max_grad_norm: 2.0
lr: 2.0e-5
warmup_steps: 0.1
seed: 19980406
gradient_accumulation_steps: 1
val_check_interval: 1
max_tokens_to_generate: 10
