## data
dev_dir: /home/guest/r11944026/research/ic-ralm-odqa/in-context-ralm/reproduce_retrieval/result/nq-dev
# dev_dir: /home/guest/r11944026/research/ic-ralm-odqa/in-context-ralm/reproduce_retrieval/result/nq-test
dev_file: formatted-ms2.nq-dev.json
# dev_file: formatted-ms2.nq-test.hits-100-debug.json
dataset_name: nq
empty_doc: False
data_size: "debug"
ckpt_dir: ckpt
runid_to_eval: nazxhkuy # TODO

eval_steps: 242
max_eval_steps: 1214

## model
resume_training: 
resume_path:
resume_wandb_id:
doc_encoder_type: dpr # dpr, contriever, bert...
query_encoder_type: dpr # dpr, contriever, bert...
base_index_dir: embeddings
# query_encoder: wandb/run-20240513_225200-ja1uhk3w/files/step-2506/query_encoder/
query_encoder: facebook/dpr-question_encoder-single-nq-base # facebook/contriever , facebook/dpr-question_encoder-single-nq-base , google-bert/bert-base-uncased
lm_model: google/flan-t5-large
# gpt2, google/flan-t5-large, huggyllama/llama-7b, meta-llama/Meta-Llama-3-8B-Instruct
quantized: False
model_parallelism: False
## training
max_round: 1
k: 5
per_device_eval_batch_size: 6 # 8 ok
eval_llm_batch_size: 13
num_exemplars: 1
# debug: set num_worker=0, pin_memory=False
num_workers: 4
pin_memory: True
auth_token: None
cache_dir: cache
seed: 19980406
gradient_accumulation_steps: 1
max_tokens_to_generate: 10
# old_query_encoder_path: wandb/run-20240510_020643-s817q8kg
# eval_steps: 2000
# max_eval_steps: 10000
# old_query_encoder_path: wandb/run-20240510_021133-xpwtaz9g
# eval_steps: 2500
# max_eval_steps: 12500
# old_query_encoder_path: wandb/run-20240510_014412-ggch6mbr
# eval_steps: 1000
# max_eval_steps: 5000