## data
train_file: /home/guest/r11944026/research/ic-ralm-odqa/in-context-ralm/reproduce_retrieval/result/trivia-train/formatted-ms2.trivia-train.size-90447.json
dev_file: /home/guest/r11944026/research/ic-ralm-odqa/in-context-ralm/reproduce_retrieval/result/trivia-dev/formatted-ms2.trivia-dev.size-11313.json
test_file: /home/guest/r11944026/research/ic-ralm-odqa/in-context-ralm/reproduce_retrieval/result/trivia-test/formatted-ms2.trivia-test.size-3610.json

# target path
# train_index_path: embeddings/trivia/dpr-multiset/train_90447_norm.pt # embeddings/dpr/train_10000.pt  dpr-multiset, dpr-multiset-new
train_index_path: embeddings/trivia/dpr-multiset/train_90447_norm.pt # embeddings/dpr/train_10000.pt  dpr-multiset, dpr-multiset-new
dev_index_path: embeddings/trivia/dpr-multiset/dev_11313_norm.pt # embeddings/dpr/dev_1000.pt  dpr
test_index_path: embeddings/trivia/dpr-multiset/test_3610_norm.pt # embeddings/dpr/dev_1000.pt  dpr
empty_index_path: embeddings/trivia/dpr-multiset/empty_doc.pt

## training
encoder_type: dpr-multiset # dpr, contriever, bert, dpr-multiset
retriever_model: facebook/dpr-ctx_encoder-multiset-base  # facebook/dpr-ctx_encoder-single-nq-base , facebook/contriever , google-bert/bert-base-uncased , facebook/dpr-ctx_encoder-multiset-base
cache_dir: cache
seed: 19980406

# preprocess option
on_train: False
on_dev: True
on_test: False
on_empty: False
extract: False
train_k: 
dev_k: 
test_k: 
normalize: False
rm_all_neg: False
most_positive: False

make_test_data_from_dev: True