## data
dev_dir: /home/guest/r11944026/research/ic-ralm-odqa/in-context-ralm/reproduce_retrieval/result/hotpot-dev
dev_file: formatted-ms2.hotpot-dev.json
dataset_name: hotpot
empty_doc: False
data_size: "1000"

## model
doc_encoder_type: bert # dpr, contriever, bert...
query_encoder_type: bert # dpr, contriever, bert...
base_index_dir: embeddings/trivia
# query_encoder: wandb/run-20240513_225200-ja1uhk3w/files/step-2506/query_encoder/
query_encoder: google-bert/bert-base-uncased # facebook/contriever , facebook/dpr-question_encoder-single-nq-base , google-bert/bert-base-uncased
lm_model: google/flan-t5-large
# gpt2, google/flan-t5-large, huggyllama/llama-7b, meta-llama/Meta-Llama-3-8B-Instruct
quantized: False
model_parallelism: False
## training
max_round: 1
k: 1
per_device_eval_batch_size: 6 # 8 ok
eval_llm_batch_size: 13
num_exemplars: 1
# debug: set num_worker=0, pin_memory=False
num_workers: 4
pin_memory: True
auth_token: None
cache_dir: cache
seed: 19980406
gradient_accumulation_steps: 1
max_tokens_to_generate: 10